# This holds the configuration information
# using this config file will create KLCv3.0 compatible footprints.

placement_tolerance: 0.05
manufacturing_tolerance: 0.1

fp_name_format_string: '{prefix:s}_{code_imperial:s}_{code_metric:s}Metric{suffix:s}'
fp_name_non_metric_format_string: '{prefix:s}_{code_imperial:s}{suffix:s}'

fp_name_tantal_format_string: '{prefix:s}_EIA-{code_metric:s}_{code_letter:s}{suffix:s}'

3d_model_prefix: '${KISYS3DMOD}/'


fab_outline: 'typical' # typical | max | min
fab_polarity_min_size: 0.3
fab_polarity_max_size: 1
fab_polarity_factor: 0.25

silk_clearance_small_parts: 0.1
