3d_model_prefix: '${KISYS3DMOD}/'

silk_line_width: 0.12
silk_pad_clearance: 0.2
silk_fab_offset: 0.11
silk_line_lenght_min: 0.2
allow_silk_below_part: 'tht' # tht | smd | all | none

fab_line_width: 0.1
fab_pin1_marker_length: 1
fab_bevel_size_absolute: 1 # Bevel size of footprints in mm
fab_bevel_size_relative: 0.25 # Bevel size of footprints relative to package size

courtyard_line_width: 0.05
courtyard_grid: 0.01
courtyard_offset:
    default: 0.25
    connector: 0.5
    bga: 1

edge_cuts_line_width: 0.12

# IPC-7351C will most likely suggest the use of rounded rectangle pads
# with 25% radius ratio but at a maximum of 0.25mm
round_rect_max_radius: 0.25
round_rect_radius_ratio: 0.25

references:
    -
          layer: 'F.SilkS'
          position_y: 'outside_top' # outside_top | inside | outside_bottom
          size: [1,1]
          fontwidth: 0.15
    -
          layer: 'F.Fab'
          position_y: 'inside' # outside_top | inside | outside_bottom
          size_max: [1,1]
          size_min: [0.25, 0.25]
          thickness_factor: 0.15
          # size: [1,1]
          # fontwidth: 0.15
values:
    -
          layer: 'F.Fab'
          position_y: 'outside_bottom' # outside_top | inside | outside_bottom
          size: [1,1]
          fontwidth: 0.15
